### ISSUE TITLE
ノーパソ壊れた

### ISSUE THREAD

**Issue by 35enidoi** [35enidoi/35enidoi#8]
なんで？

**Comment by Yon4800** [comment]
どんな感じに壊れてるの？

**Comment by 35enidoi** [comment]
モニターの接合部分のネジが死んでさらにモニターと繋がってる金属も折れてる
畳めないだけで動作は可能

**Comment by Yon4800** [comment]
なるほど...
物理的な破損はちょっと修復は難しいよな...
確か中古だよね

**Comment by 35enidoi** [comment]
中古で買った
安物買いの銭失いってやつかな？

**Comment by Yon4800** [comment]
多分...
~~SBC買お(ry~~

**Comment by 35enidoi** [comment]
新しいノートパソコンを買ってもらったので閉じます
